#!/usr/bin/env python3
"""Render examples/README.md from the annotated profile files.

Invoked via gen-example-docs.sh. Reads every examples/profiles/*.yml, builds a
flag coverage matrix plus a per-profile section. The set of matrix columns is the
union of `answers` keys across all profiles, so adding a flag to a profile adds a
column automatically — no edits here.
"""
from __future__ import annotations

import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROFILES_DIR = ROOT / "examples" / "profiles"
OUT = ROOT / "examples" / "README.md"

# Stable, human-meaningful column order. Any answer key not listed here is
# appended alphabetically, so nothing silently disappears from the matrix.
COLUMN_ORDER = [
    "include_frontend",
    "include_example_domain",
    "auth",
    "mailer",
    "verification_method",
    "caching",
    "eventing",
    "payments",
    "push_notifications",
    "object_storage",
    "agent_tooling",
]

# Compact header labels so the table stays readable.
COLUMN_LABELS = {
    "include_frontend": "frontend",
    "include_example_domain": "example",
    "verification_method": "verify",
    "push_notifications": "push",
    "object_storage": "storage",
    "agent_tooling": "agent",
}


def cell(value) -> str:
    """Render an answer value for the matrix."""
    if value is True:
        return "✓"
    if value is False or value in (None, "none"):
        return "·"
    return str(value)


def load_profiles() -> list[dict]:
    profiles = []
    for path in sorted(PROFILES_DIR.glob("*.yml")):
        data = yaml.safe_load(path.read_text()) or {}
        data["_name"] = path.stem
        if "answers" not in data:
            sys.exit(f"profile {path.name} has no `answers:` block")
        if "meta" not in data:
            sys.exit(f"profile {path.name} has no `meta:` block")
        profiles.append(data)
    if not profiles:
        sys.exit("no profiles found in examples/profiles/")
    return profiles


def columns(profiles: list[dict]) -> list[str]:
    keys = set()
    for p in profiles:
        keys.update(p["answers"].keys())
    keys.discard("project_name")  # identity, not a behavior flag
    ordered = [k for k in COLUMN_ORDER if k in keys]
    ordered += sorted(k for k in keys if k not in COLUMN_ORDER)
    return ordered


def render(profiles: list[dict]) -> str:
    cols = columns(profiles)
    out: list[str] = []
    out.append("<!-- GENERATED by scripts/gen-example-docs.sh — DO NOT EDIT. -->")
    out.append("")
    out.append("# Example profiles")
    out.append("")
    out.append(
        "Curated renderings of the template. Each profile is an answer set that "
        "guards a specific code path. The pre-task snapshot lives in "
        "`examples/rendered/<profile>/` (browse it for a real generated project); "
        "CI validates the post-task build + tests for every profile."
    )
    out.append("")
    out.append("## Coverage matrix")
    out.append("")
    header = ["profile"] + [COLUMN_LABELS.get(c, c) for c in cols]
    out.append("| " + " | ".join(header) + " |")
    out.append("|" + "|".join(["---"] * len(header)) + "|")
    for p in profiles:
        row = [f"[`{p['_name']}`](#{p['_name']})"]
        row += [cell(p["answers"].get(c)) for c in cols]
        out.append("| " + " | ".join(row) + " |")
    out.append("")
    out.append("Legend: `✓` enabled · `·` off/none · otherwise the chosen value.")
    out.append("")
    out.append("## Profiles")
    out.append("")
    for p in profiles:
        meta = p["meta"]
        out.append(f"### {p['_name']}")
        out.append("")
        out.append(f"**{meta.get('title', p['_name'])}** — {meta.get('purpose', '')}")
        out.append("")
        if meta.get("guards"):
            out.append("Guards:")
            out.extend(f"- {g}" for g in meta["guards"])
            out.append("")
        if meta.get("validates"):
            out.append("Validated by: " + ", ".join(f"`{v}`" for v in meta["validates"]))
            out.append("")
        out.append(f"Snapshot: [`examples/rendered/{p['_name']}/`](rendered/{p['_name']})")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    profiles = load_profiles()
    OUT.write_text(render(profiles))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(profiles)} profiles)")


if __name__ == "__main__":
    main()
