swagger_parser:
  schema_path: ../../api/openapi.yaml
  output_directory: lib
  language: dart
  json_serializer: freezed
  root_client: true
  root_client_name: RestClient
  client_postfix: Client
  default_content_type: "application/json"
  dio_options_parameter_by_default: true
  export_file: true
  put_in_folder: false
  put_clients_in_folder: false
  enums_to_json: false
  enums_parent_prefix: true
  unknown_enum_value: true
  use_freezed3: true
  mark_files_as_generated: true
